services:
  db:
    image: postgres:14.2
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/orders.csv:/db/orders.csv
    env_file:
      - .env
    networks:
      - mainNetwork
  redis:
    image: 'redis'
    ports:
      - 6379
    command: redis-server
    networks:
      - mainNetwork

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    env_file:
      - .env
    networks:
      - mainNetwork
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mainNetwork
volumes:
  db_data:

networks:
      mainNetwork:
          driver: bridge